import type { Title } from './model';
const rows = [
  [
    'After the Tide',
    'Drama',
    2025,
    108,
    'Elena Vale',
    'A lighthouse keeper and her estranged brother spend one last summer cataloging everything the sea returns.',
    'SOME THINGS ALWAYS RETURN.',
    'tide',
  ],
  [
    'Static Bloom',
    'Sci-fi',
    2024,
    96,
    'Theo Arden',
    'A sound archivist discovers a radio signal that appears only when a city falls asleep.',
    'LISTEN BETWEEN THE LINES.',
    'static',
  ],
  [
    'The Quiet Orchard',
    'Drama',
    2023,
    114,
    'Mira Sol',
    'Three generations return to a neglected orchard and discover that the harvest is the easy part.',
    'ROOTS RUN DEEP.',
    'orchard',
  ],
  [
    'Night Service',
    'Thriller',
    2025,
    101,
    'Jonah Reed',
    'An overnight train attendant finds a passenger whose destination does not exist on any timetable.',
    'THE LAST STOP IS MISSING.',
    'night',
  ],
  [
    'Small Hours Club',
    'Comedy',
    2024,
    92,
    'Nina Hart',
    'Four strangers share the last table at an all-night diner and accidentally start a very small revolution.',
    'EVERYONE HAS A LATE NIGHT STORY.',
    'hours',
  ],
  [
    'Paper Satellites',
    'Animation',
    2025,
    84,
    'Ari Flores',
    'A young mapmaker folds a paper city that begins to change the town outside her window.',
    'A WORLD WAITING TO UNFOLD.',
    'paper',
  ],
  [
    'A Map of Elsewhere',
    'Adventure',
    2022,
    118,
    'Leo Finch',
    'Two reluctant companions follow a hand-drawn atlas through towns erased from modern maps.',
    'TAKE THE LONG WAY HOME.',
    'map',
  ],
  [
    'Soft Machine Summer',
    'Sci-fi',
    2025,
    105,
    'Ada North',
    'A repair technician befriends an obsolete machine that remembers a summer nobody else does.',
    'MEMORY HAS ITS OWN WEATHER.',
    'summer',
  ],
  [
    'The Last Good Table',
    'Comedy',
    2023,
    99,
    'Rosa Bell',
    'A family restaurant hosts its final dinner, with every former regular arriving at the wrong time.',
    'ONE MORE ROUND.',
    'table',
  ],
  [
    'Blue Window Theory',
    'Mystery',
    2024,
    112,
    'Emil West',
    'A photographer notices the same blue window appearing in pictures taken decades apart.',
    'LOOK A LITTLE CLOSER.',
    'blue',
  ],
  [
    'Letters from a Volcano',
    'Documentary',
    2025,
    87,
    'Iris Moss',
    'An imagined field journal follows scientists and residents living beside a restless mountain.',
    'LIFE ON THE EDGE OF CHANGE.',
    'volcano',
  ],
  [
    'In the Middle of Monday',
    'Drama',
    2024,
    103,
    'Sam Rivers',
    'A missed appointment sends a retired teacher on a wandering day through her changing neighborhood.',
    'AN ORDINARY DAY, OPENED WIDE.',
    'monday',
  ],
  [
    'Velvet Transit',
    'Thriller',
    2023,
    98,
    'Noel Ash',
    'A bicycle courier accepts a delivery whose instructions change at every intersection.',
    'KEEP MOVING.',
    'velvet',
  ],
  [
    'The Garden in Orbit',
    'Sci-fi',
    2022,
    121,
    'Jules Stone',
    'A botanist on a remote station must decide which of Earth’s last seeds deserve a second chance.',
    'GROW SOMETHING WORTH KEEPING.',
    'garden',
  ],
  [
    'Two Tickets West',
    'Adventure',
    2025,
    107,
    'Lena Bay',
    'Childhood friends reunite on a bus journey with an itinerary neither is willing to explain.',
    'SOME DISTANCES BRING YOU CLOSER.',
    'west',
  ],
  [
    'Clouds Made of String',
    'Animation',
    2024,
    79,
    'Oren Lake',
    'A village of kite makers learns to repair the sky after a storm tangles the clouds.',
    'EVERY KNOT HAS A STORY.',
    'cloud',
  ],
  [
    'Borrowed Sunshine',
    'Comedy',
    2022,
    94,
    'Ella Pine',
    'A chronically unlucky house sitter tries to keep an impossible collection of plants alive for one week.',
    'A LITTLE LIGHT GOES A LONG WAY.',
    'sunshine',
  ],
  [
    'A Room for Echoes',
    'Mystery',
    2025,
    109,
    'Kai Frost',
    'An acoustician surveys an empty concert hall where rehearsals seem to continue after midnight.',
    'THE ROOM REMEMBERS.',
    'echo',
  ],
  [
    'Salt & Asphalt',
    'Documentary',
    2023,
    90,
    'Milo Sage',
    'A fictional portrait of the night crews who keep a coastal road open through winter.',
    'THE ROAD NEVER SLEEPS.',
    'salt',
  ],
  [
    'Tomorrow, in Pieces',
    'Drama',
    2025,
    116,
    'Alma Wren',
    'A ceramicist reconstructs a broken commission while the people around her quietly rebuild their own lives.',
    'BEGIN WITH WHAT REMAINS.',
    'pieces',
  ],
] as const;
export const catalog: Title[] = rows.map((r, i) => ({
  id: `film-${String(i + 1).padStart(2, '0')}`,
  name: r[0],
  genre: r[1],
  year: r[2],
  minutes: r[3],
  director: r[4],
  description: r[5],
  tagline: r[6],
  palette: r[7],
  motif: i % 4,
  watch: null,
}));
export const genres = [...new Set(catalog.map((t) => t.genre))].sort();
